### ISSUE TITLE
okhttp (almost) outdated

### ISSUE THREAD

**Issue by oliverhausler** [socketio/engine.io#419]
engine.io uses an almost outdated okhttp-ws library (3.0.1). retrofit and other libraries which also use okhttp use much newer versions (up to 3.4.1), which leads to issues, if one of the other libraries brings in a version newer than 3.3.1. retrofit is still at 3.0.0 so we are still fine in most cases, but engine.io should be ready to release a newer version as soon as retrofit switches, or a lot of apps will break.

More specifically, I have that WebSocketCall has been changed around ln 108 by the okhttp guys, which breaks socket.io when an okhttp library after Jun 21 is used.

The offending commit is here: https://github.com/square/okhttp/commit/576408374d58a3e9a63714b6f7761cb42a315102#diff-6f6bc59233fb2201c3382a12e62e4b03

And this is the call which will fail, and if it fails, WS fails entirely:

```
09-02 20:48:22.024 28423-28561/live.attach.testcontainer E/AndroidRuntime: FATAL EXCEPTION: EventThread
                                                                           Process: live.attach.testcontainer, PID: 28423
                                                                           java.lang.NoSuchMethodError: okhttp3.internal.Internal.callEnqueue
                                                                               at okhttp3.ws.WebSocketCall.enqueue(WebSocketCall.java:108)
                                                                               at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:73)
                                                                               at io.socket.engineio.client.Transport$1.run(Transport.java:75)
                                                                               at io.socket.thread.EventThread.exec(EventThread.java:50)
                                                                               at io.socket.engineio.client.Transport.open(Transport.java:70)
                                                                               at io.socket.engineio.client.Socket.probe(Socket.java:458)
                                                                               at io.socket.engineio.client.Socket.onOpen(Socket.java:471)
                                                                               at io.socket.engineio.client.Socket.onHandshake(Socket.java:512)
                                                                               at io.socket.engineio.client.Socket.onPacket(Socket.java:485)
                                                                               at io.socket.engineio.client.Socket.access$900(Socket.java:30)
                                                                               at io.socket.engineio.client.Socket$5.call(Socket.java:299)
                                                                               at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                               at io.socket.engineio.client.Transport.onPacket(Transport.java:127)
                                                                               at io.socket.engineio.client.transports.Polling.access$700(Polling.java:17)
                                                                               at io.socket.engineio.client.transports.Polling$2.call(Polling.java:124)
                                                                               at io.socket.engineio.parser.Parser.decodePayload(Parser.java:251)
                                                                               at io.socket.engineio.client.transports.Polling._onData(Polling.java:134)
                                                                               at io.socket.engineio.client.transports.Polling.onData(Polling.java:106)
                                                                               at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:113)
                                                                               at io.socket.thread.EventThread$2.run(EventThread.java:75)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                               at java.lang.Thread.run(Thread.java:841)
```

**Comment by darrachequesne** [comment]
Doesn't that issue rather belong to [engine.io-client-java](https://github.com/socketio/engine.io-client-java)?

Besides, the maven dependency seem to be up-to-date:
```java
    <dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>okhttp-ws</artifactId>
      <version>3.4.1</version>
    </dependency>
```

**Comment by oliverhausler** [comment]
@darrachequesne Yes, you are right. But if the maven dependency is up-to-date now, then this is obsolete I assume. So I'm closing it.
